import { z } from "zod"

/**
 * @interface DecisionNode
 * @description Represents a decision node in the ArangoDB graph. Carries the
 *   optional per-perspective verdict breakdown used to score historical
 *   perspective performance (see queryPerspectivePerformance).
 */
export interface DecisionNode {
  _key?: string
  userId: string
  asset: string
  category: string
  decision: "buy" | "sell" | "hold"
  side: "long" | "short" | "no_trade"
  confidence: number
  tradePlan: unknown
  autonomyDecision: "auto" | "approve"
  timestamp: string
  // reason: per-decision per-perspective verdicts; the planning layer owns the
  // shape — kept `unknown` here so this DB layer never couples to planning.
  perspectiveBreakdown?: unknown
}

/**
 * @interface SignalNode
 * @description Represents a signal node generated by the system.
 */
export interface SignalNode {
  _key?: string
  factor: string
  signalType: string
  description: string
  strength: number
  timestamp: string
}

/**
 * @interface OutcomeNode
 * @description Represents the outcome node of a trade.
 */
export interface OutcomeNode {
  _key?: string
  result: "profit" | "loss" | "breakeven" | "cancelled"
  pnlUsdc?: number
  pnlPercent?: number
  exitPrice?: number
  exitReason?: string
  timestamp: string
}

/**
 * @interface AssetNode
 * @description Represents an asset node in the graph.
 */
export interface AssetNode {
  _key: string
  name: string
  category: string
}

/**
 * @constant RiskThresholdsDocSchema
 * @description Zod schema for the risk thresholds document stored in the database.
 */
export const RiskThresholdsDocSchema = z.object({
  _key: z.string().optional(),
  userId: z.string(),
  confidence_threshold: z.number().int().min(0).max(100).default(70),
  max_position_usdc: z.number().min(0).default(100),
  max_leverage: z.number().min(1).default(10),
  risk_per_trade_percent: z.number().min(0).max(100).default(1),
})
export type RiskThresholdsDoc = z.infer<typeof RiskThresholdsDocSchema>

/**
 * @interface GraphMemoryEdge
 * @description Represents an edge connecting nodes in the graph memory.
 */
export interface GraphMemoryEdge {
  _from: string
  _to: string
  collection: string
  weight?: number
  timestamp?: string
}

/**
 * @interface DDReportNode
 * @description Represents a persisted DD report document in ArangoDB.
 */
export interface DDReportNode {
  _key?: string
  runId: string
  userId: string
  walletAddress: string
  asset: string
  report: Record<string, unknown>
  timestamp: string
  processingTimeMs: number
}

/**
 * @constant GraphCollectionNames
 * @description Collection names used in the ArangoDB graph.
 */
export const GraphCollectionNames = {
  DECISIONS: "decisions",
  SIGNALS: "signals",
  OUTCOMES: "outcomes",
  ASSETS: "assets",
  DD_REPORTS: "dd_reports",
  EDGE_ANALYZED: "decision_analyzed",
  EDGE_TRIGGERED_BY: "decision_triggered_by",
  EDGE_RESULTED_IN: "decision_resulted_in",
  EDGE_ASSET_BELONGS_TO: "asset_belongs_to",
  EDGE_HAS_FACTORREPORT: "decision_has_factorreport",
} as const
